version: 0.0
os: linux

files:
  - source: /scripts/Dockerfile
    destination: /opt

  - source: /target/login##1.0.war
    destination: /opt

hooks:

  ApplicationStop:
    - location: scripts/removecontainer.sh
      timeout: 300
      runas: root

    - location: scripts/removeimages.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
       
  ApplicationStart:
    - location: scripts/run_docker_commands.sh
      timeout: 300
      runas: root
